name: CI

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build:
        - android
        include:
        - build: android
          os: ubuntu-22.04
          arch: aarch64-linux-android32
        - build: android-recovery
          os: ubuntu-22.04
          arch: aarch64-linux-android32

    env:
      CI_TARGET_BUILD: ${{ matrix.build }}
      CI_TARGET_ARCH: ${{ matrix.arch }}
      CC: ${{ matrix.cc }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Install dependencies
      run: ${{matrix.shell}} ./ci/actions-install.sh
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      with:
        limit-access-to-actor: true
    - name: Build
      run:  ${{matrix.shell}} ./ci/actions-build.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.build }}
        path: fio
